home/urls.py
from django.urls import path, include
from . import viewDep, viewsPais, viewMunicipio
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    #paises
    path('', viewsPais.HomeTemplateView.as_view(), name='home'),
    path('pais/', viewsPais.lista.as_view(), name='listapais'),
    path('pais/<int:pk>/', viewsPais.detalle.as_view(), name='detallepais'),
    path('pais/crear/', viewsPais.crear.as_view(), name='crearpais'),
    path('pais/<int:pk>/actualizar/', viewsPais.actualizar.as_view(), name='actualizarpais'),
    path('pais/<int:pk>/eliminar/', viewsPais.eliminar.as_view(), name='eliminarpais'),
    
    path('departamento/', viewDep.lista.as_view(), name='listadepto'),
    path('departamento/<int:pk>/', viewDep.detalle.as_view(), name='detalledepto'),
    path('departamento/crear/', viewDep.crear.as_view(), name='creardepto'),
    path('departamento/<int:pk>/actualizar/', viewDep.actualizar.as_view(), name='actualizardepto'),
    path('departamento/<int:pk>/eliminar/', viewDep.eliminar.as_view(), name='eliminardepto'),
    
    path('municipio/', viewMunicipio.lista.as_view(), name='listamuni'),
    path('municipio/<int:pk>/', viewMunicipio.detalle.as_view(), name='detallemuni'),
    path('municipio/crear/', viewMunicipio.crear.as_view(), name='crearmuni'),
    path('municipio/<int:pk>/actualizar/', viewMunicipio.actualizar.as_view(), name='actualizarmuni'),
    path('municipio/<int:pk>/eliminar/', viewMunicipio.eliminar.as_view(), name='eliminarmuni'),
    
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='listapais'), name='logout'),
    path('register/', viewsPais.RegisterView.as_view(), name='register'),

    path('api/', include('home.urlsAPI')),

    
]

laboratorio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls"), name='home'),

]

home/models.py
from django.db import models


class Pais(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Departamento(models.Model):
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Municipio(models.Model):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        /* Estilos globales */
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f0f0f0; /* Color de fondo general */
}

header {
    background-color: #333; /* Color de fondo del encabezado */
    color: #fff; /* Color del texto en el encabezado */
    padding: 10px 0; /* Espaciado interior en el encabezado */
}

nav ul {
    list-style: none;
    padding: 0;
}

nav ul li {
    display: inline;
    margin-right: 20px; /* Espacio entre elementos de navegación */
}

nav ul li a {
    text-decoration: none;
    color: #fff; /* Color de texto para los enlaces de navegación */
    font-weight: bold; /* Texto en negrita */
}

/* Estilos para los enlaces cuando se pasan por encima */
nav ul li a:hover {
    color: #ff5722; /* Cambia el color al pasar el mouse */
}

/* Estilos para el contenido principal */
.container {
    max-width: 960px;
    margin: 0 auto;
    padding: 20px;
    background-color: #fff; /* Color de fondo del contenido principal */
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Sombra ligera */
}

/* Estilos para el título de la página */
h1 {
    font-size: 24px;
    margin-bottom: 20px;
}

/* Estilos para los enlaces de navegación en el encabezado */
header nav ul li a {
    text-transform: uppercase; /* Texto en mayúsculas */
}

    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title%}
    <title>Document</title>
    {% endblock %}

</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'listapais' %}">Paises</a></li>
                <li><a href="{% url 'listadepto' %}">Departamentos</a></li>
                <li><a href="{% url 'listamuni' %}">Municipios</a></li>
                <li>
                    {% if user.is_authenticated%}
                    <a href="{% url 'logout' %}">Logout</a>
                    
                    {% else %}
                    <a href="{% url 'login' %}">Login</a>
                    <a href="{% url 'register' %}">Registrar</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </header>
    {% block content%}
    hola mundo
    {% endblock %}
</body>
</html>

home/templates/departamento/actualizar.html
{% extends "base.html" %}
{% block title%}
    <title>Actualizar Departamento</title>
{% endblock %}
{% block content%}
    <h1>Actualizar Departamento</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

home/templates/departamento/crear.html
{% extends "base.html" %}
{% block title%}
    <title>Crear Departamento</title>
{% endblock %}
{% block content%}
    <h1>Crear Departamento</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

home/templates/departamento/detalle.html
{% extends "base.html" %}
{% block content%}
    <h1>Detalle del Departamento</h1>
    <p><strong>Nombre:</strong> {{ departamento.nombre }}</p>
    <p><strong>País:</strong> {{ departamento.pais }}</p>
    {% if perms.catalogo.change_departamento %}
    <a href="{% url 'actualizardepto' departamento.pk %}">Editar Departamento</a>
   {%endif%}
    {% if perms.catalogo.delete_departamento %}
    <a href="{% url 'eliminardepto' departamento.pk %}">Eliminar Departamento</a>
  {%endif%}
{% endblock %}

home/templates/departamento/eliminar.html
{% extends "base.html" %}
{% block content%}
    <h1>¿Estás seguro de que deseas eliminar este departamento?</h1>
    <p><strong>Nombre:</strong> {{ departamento.nombre }}</p>
    <p><strong>País:</strong> {{ departamento.pais }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Sí, Eliminar</button>
    </form>
    <a href="{% url 'detalledepto' departamento.pk %}">Cancelar</a>
{% endblock %}

home/templates/departamento/lista.html
{% extends "base.html" %} {% block title%}
<title>Lista de Departamentos</title>
{% endblock %} {% block content%}

<form method="get" action="{% url 'listadepto' %}">
  <input
    type="text"
    name="departamento"
    value="{{ query }}"
    placeholder="Buscar país..."
  />
  <input type="submit" value="Buscar" />
</form>

<h1>Lista de Departamentos</h1>
<ul>
  {% for departamento in departamentos %}
  <li>
    {% if perms.home.view_departamento%}
    <a href="{% url 'detalledepto' departamento.pk %}"
      >{{ departamento.nombre }}</a
    >
    {%else%}
    <a>{{ departamento.nombre }}</a>
    {%endif%}
  </li>
  {% endfor %}
</ul>
{% if perms.home.add_departamento%}
<a href="{% url 'creardepto' %}">Crear Departamento</a>
  {%endif%}

{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if paises.has_previous %}
    <li class="page-item">
      <a
        class="page-link"
        href="?pais={{ query }}&page={{ paises.previous_page_number }}"
        >«</a
      >
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">«</a>
    </li>
    {% endif %} {% for i in paginator.page_range %}
    <li class="page-item {% if paises.number == i %}active{% endif %}">
      <a class="page-link" href="?pais={{ query }}&page={{ i }}">{{ i }}</a>
    </li>
    {% endfor %} {% if paises.has_next %}
    <li class="page-item">
      <a
        class="page-link"
        href="?pais={{ query }}&page={{ paises.next_page_number }}"
        >»</a
      >
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">»</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %} {% endblock %}

home/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <p>login correctamente</p>
{% endblock %}
```

home/templates/login.html
{% extends "base.html" %}
{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

home/templates/municipio/actualizar.html
{% extends "base.html" %}
{% block title%}
    <title>Actualizar Municipio</title>
{% endblock %}
{% block content%}
    <h1>Actualizar Municipio</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

home/templates/municipio/crear.html
{% extends "base.html" %}
{% block title%}
    <title>Crear Municipio</title>
{% endblock %}
{% block content%}
    <h1>Crear Municipio</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

home/templates/municipio/detalle.html
{% extends "base.html" %}
{% block content%}
    <h1>Detalle del Municipio</h1>
    <p><strong>Nombre:</strong> {{ municipio.nombre }}</p>
    <p><strong>Departamento:</strong> {{ municipio.departamento }}</p>
    {% if perms.catalogo.change_municipio%}
    <a href="{% url 'actualizarmuni' municipio.pk %}">Editar Municipio</a>
   {%endif%}
    {% if perms.catalogo.delete_municipio%}
    <a href="{% url 'eliminarmuni' municipio.pk %}">Eliminar Municipio</a>
  {%endif%}
{% endblock %}

home/templates/municipio/eliminar.html
{% extends "base.html" %}
{% block content%}
    <h1>¿Estás seguro de que deseas eliminar este Municipio?</h1>
    <p><strong>Nombre:</strong> {{ municipio.nombre }}</p>
    <p><strong>Departamento:</strong> {{ municipio.departamento }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Sí, Eliminar</button>
    </form>
    <a href="{% url 'detallemuni' municipio.pk %}">Cancelar</a>
{% endblock %}

home/templates/municipio/lista.html
{% extends "base.html" %} {% block title%}
<title>Lista de Municipios</title>
{% endblock %} {% block content%}

<form method="get" action="{% url 'listamuni' %}">
  <input
    type="text"
    name="municipio"
    value="{{ query }}"
    placeholder="Buscar país..."
  />
  <input type="submit" value="Buscar" />
</form>



<h1>Lista de Municipios</h1>
<ul>
  <li>
    {% for municipio in municipios %} 
    {% if perms.home.view_municipio %}
    <a href="{% url 'detallemuni' municipio.pk %}">{{ municipio.nombre }}</a>
    {%else%} 
      <a>{{ municipio.nombre }}</a>
    {%endif%}
  </li>
  {% endfor %}
</ul>
{% if perms.home.add_municipio%}
<a href="{% url 'crearmuni' %}">Crear Municipio</a>
  {%endif%}

{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if paises.has_previous %}
    <li class="page-item">
      <a
        class="page-link"
        href="?pais={{ query }}&page={{ paises.previous_page_number }}"
        >«</a
      >
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">«</a>
    </li>
    {% endif %} {% for i in paginator.page_range %}
    <li class="page-item {% if paises.number == i %}active{% endif %}">
      <a class="page-link" href="?pais={{ query }}&page={{ i }}">{{ i }}</a>
    </li>
    {% endfor %} {% if paises.has_next %}
    <li class="page-item">
      <a
        class="page-link"
        href="?pais={{ query }}&page={{ paises.next_page_number }}"
        >»</a
      >
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">»</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %} {% endblock %}

home/templates/pais/actualizar.html
{% extends "base.html" %}
{% block title%}
    <title>Actualizar Pais</title>
{% endblock %}
{% block content%}
    <h1>Actualizar Pais</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

home/templates/pais/crear.html
{% extends "base.html" %}
{% block title%}
    <title>Crear Pais</title>
{% endblock %}
{% block content%}
    <h1>Crear Pais</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

home/templates/pais/detalle.html
{% extends "base.html" %}
{% block content%}
    <h1>Detalle del Pais</h1>
    <p><strong>Nombre:</strong> {{ pais.nombre }}</p>
    {% if perms.catalogo.change_pais%}
    <a href="{% url 'actualizarpais' pais.pk %}">Editar Pais</a>
   {%endif%}
    {% if perms.catalogo.delete_pais%}
    <a href="{% url 'eliminarpais' pais.pk %}">Eliminar Pais</a>
  {%endif%}
{% endblock %}

home/templates/pais/eliminar.html
{% extends "base.html" %}
{% block content%}
    <h1>¿Estás seguro de que deseas eliminar este Pais?</h1>
    <p><strong>Nombre:</strong> {{ pais.nombre }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Sí, Eliminar</button>
    </form>
    <a href="{% url 'detallepais' pais.pk %}">Cancelar</a>
{% endblock %}

home/templates/pais/listapais.html
{% extends "base.html" %} {% block title%}
<title>Lista de Paises</title>
{% endblock %} {% block content%}

<form method="get" action="{% url 'listapais' %}">
  <input type="text" name="pais" value="{{ query }}" placeholder="Buscar país...">
  <input type="submit" value="Buscar">
</form>

<h1>Lista de Paises</h1>
<ul>
  {% for pais in paises %}

  <li>
    {% if perms.home.view_pais %}
    <a href="{% url 'detallepais' pais.pk %}">{{ pais.nombre }}</a>
    {% else %}
    <a>{{ pais.nombre }}</a>
    {% endif %}
  </li>
  
  {% endfor %}
</ul>
{% if perms.home.add_pais %}
<a href="{% url 'crearpais' %}">Crear Pais</a>
{%endif%}

{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if paises.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?pais={{ query }}&page={{ paises.previous_page_number }}">«</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">«</a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      <li class="page-item {% if paises.number == i %}active{% endif %}">
        <a class="page-link" href="?pais={{ query }}&page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}
    {% if paises.has_next %}
      <li class="page-item">
        <a class="page-link" href="?pais={{ query }}&page={{ paises.next_page_number }}">»</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">»</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %} {% endblock %}

home/templates/registro.html
{% extends "base.html" %}
{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}